  # Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference

orbs:
  docker: circleci/docker@1.7.0


version: 2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/build:
          attach-at: ./ 
          dockerfile: Dockerfile.oracles 
          lint-dockerfile: true 
          path: images
          image: oracles 

workflows:
  commit:
    jobs:
      - example-job
